# Generated by Django 3.1.6 on 2021-05-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='updated_image',
            field=models.ImageField(upload_to='myimage'),
        ),
    ]
