# Generated by Django 3.1.6 on 2021-05-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('cluster', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=250)),
                ('image_hash', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('updated_image', models.CharField(max_length=500)),
            ],
        ),
    ]
