# Generated by Django 3.1.6 on 2021-05-22 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210519_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='lat',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusters',
            name='lon',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
